---
ID: "60ca153a-0226-4ce7-aeff-2bd98d138521"
Parent: "aab24a43-f77e-4fa2-8156-747a8a8ac206"
Template: "aab24a43-f77e-4fa2-8156-747a8a8ac206"
Path: /sitecore/templates/Feature/MedPro/Manual Form/Builder Table/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230811T051241Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a64c67bc-6f1f-46c9-af64-55496f34d5bc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230811T051241Z
