---
ID: "782531e6-ab91-4426-b500-77c374bb1f52"
Parent: "8d1d68db-85e5-497e-93ba-74ecb94f5555"
Template: "8d1d68db-85e5-497e-93ba-74ecb94f5555"
Path: /sitecore/templates/Feature/MedPro/Manual Form/Load Form/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230811T051301Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9b1f9d68-07f5-4e60-9df9-2bc7bd5a1609"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230811T051301Z
